### ISSUE TITLE
typos to fix

### ISSUE THREAD

**Issue by soooh** [journ220/journ220.github.io#1]
Discussed via Zoom

- [x] `Use the class link for bcourses` - capitalize C in bCourses
- [x] `Officer hours`
- [x] link to Soo's Calendly
- [x] `endeavour` no `u`
- [x] `Final projedcts due`
- [x] `>We'll adhere to Berkeley`
- [x] `I can hold a live Zoom` (change to "We")
- [x] `DISABLED STUDENT'S PROGRAM` apostrophe after STUDENTS

**Comment by yolimartinez** [comment]
All fixed, thanks much for reviewing with me!
