### ISSUE TITLE
add assignment 1 work

### ISSUE THREAD

**Issue by soooh** [journ220/journ220.github.io#2]
HOMEWORK
- Submit Assignment 1 on bCourses by Jan. 30 at 11:59 pm.

REQUIRED READING BEFORE THE NEXT LECTURE
- 📄 [Find the Coaching in Criticism](https://hbr.org/2014/01/find-the-coaching-in-criticism) from HBR ([here’s a PDF](https://soooh.net/j233/readings/feedback_hbr.pdf) if you’re paywalled)

RECOMMENDED (NOT REQUIRED)
- 🎦 [“Do you believe people are doing the best they can?”](https://www.youtube.com/watch?v=w5TkA7d7eTw) — clip of Brené Brown on Russell Brand’s podcast (it’s technically a video but you can play audio in background; the closed captioning is also pretty good)

**Comment by yolimartinez** [comment]
All added!
